import 'package:muhammad_zubair_s_application4/core/app_export.dart';

class UserChargeAgreemantController extends GetxController{
List content=[
'user_recharge_agreemant_article_1'.tr,
'user_recharge_agreemant_article_1.1'.tr,
'user_recharge_agreemant_article_1.2'.tr,
'user_recharge_agreemant_article_1.3'.tr,
'user_recharge_agreemant_article_2'.tr,
'user_recharge_agreemant_article_2.1'.tr,
'user_recharge_agreemant_article_2.2'.tr,
'user_recharge_agreemant_article_2.4'.tr,
'user_recharge_agreemant_article_2.5'.tr,
'user_recharge_agreemant_article_2.6'.tr,
'user_recharge_agreemant_article_2.7'.tr,
'user_recharge_agreemant_article_3'.tr,
'user_recharge_agreemant_article_3.1'.tr,
'user_recharge_agreemant_article_3.2'.tr,
'user_recharge_agreemant_article_3.3'.tr,
'user_recharge_agreemant_article_3.4'.tr,
'user_recharge_agreemant_article_3.5'.tr,
'user_recharge_agreemant_article_3.6'.tr,
'user_recharge_agreemant_article_4'.tr,
'user_recharge_agreemant_article_4.1'.tr,
'user_recharge_agreemant_article_4.2'.tr,
'user_recharge_agreemant_article_4.3'.tr,
'user_recharge_agreemant_article_4.4'.tr,
'user_recharge_agreemant_article_4.5'.tr,
'user_recharge_agreemant_article_4.6'.tr,
'user_recharge_agreemant_article_5'.tr,
'user_recharge_agreemant_article_5.1'.tr,
'user_recharge_agreemant_article_5.2'.tr,
'user_recharge_agreemant_article_6'.tr,
'user_recharge_agreemant_article_6.1'.tr,
'user_recharge_agreemant_article_6.2'.tr,
'user_recharge_agreemant_article_6.3'.tr,
'user_recharge_agreemant_article_7'.tr,
'user_recharge_agreemant_article_7.1'.tr,
'user_recharge_agreemant_article_7.2'.tr,
'user_recharge_agreemant_article_8'.tr,
'user_recharge_agreemant_article_8.1'.tr,
'user_recharge_agreemant_article_8.2'.tr,
'user_recharge_agreemant_article_9'.tr,
'user_recharge_agreemant_article_9.1'.tr,
'user_recharge_agreemant_article_10'.tr,
'user_recharge_agreemant_article_10.1'.tr,
'user_recharge_agreemant_article_11'.tr,
'user_recharge_agreemant_article_11.1'.tr,
];

}