import 'package:muhammad_zubair_s_application4/core/app_export.dart';

class LiveAgreemantController extends GetxController{

List content=[
  'live_agreement_articale_1'.tr,
  'live_agreement_articale_1.1'.tr,
  'live_agreement_articale_1.2'.tr,
  'live_agreement_articale_1.3'.tr,
  'live_agreement_articale_1.4'.tr,
  'live_agreement_articale_1.5'.tr,
  'live_agreement_articale_2'.tr,
  'live_agreement_articale_2.1'.tr,
  'live_agreement_articale_2.2'.tr,
  'live_agreement_articale_2.3'.tr,
  'live_agreement_articale_2.4'.tr,
  'live_agreement_articale_2.5'.tr,
  'live_agreement_articale_2.6'.tr,
  'live_agreement_articale_2.7'.tr,
  'live_agreement_articale_2.8'.tr,
  'live_agreement_articale_2.9'.tr,
  'live_agreement_articale_3'.tr,
  'live_agreement_articale_3.1'.tr,
  'live_agreement_articale_3.2'.tr,
  'live_agreement_articale_3.3'.tr,
  'live_agreement_articale_3.4'.tr,
  'live_agreement_articale_3.5'.tr,
  'live_agreement_articale_3.6'.tr,
  'live_agreement_articale_3.7'.tr,
  'live_agreement_articale_3.8'.tr,
  'live_agreement_articale_3.9'.tr,
  'live_agreement_articale_3.10'.tr,
  'live_agreement_articale_3.11'.tr,
  'live_agreement_articale_3.12'.tr,
  'live_agreement_articale_3.13'.tr,
  'live_agreement_articale_3.14'.tr,
  'live_agreement_articale_3.15'.tr,
  'live_agreement_articale_3.16'.tr,
  'live_agreement_articale_3.17'.tr,
  'live_agreement_articale_3.18'.tr,
  'live_agreement_articale_3.19'.tr,
  'live_agreement_articale_4'.tr,
  'live_agreement_articale_4.1'.tr,
  'live_agreement_articale_4.2'.tr,
  'live_agreement_articale_4.3'.tr,
  'live_agreement_articale_5'.tr,
  'live_agreement_articale_5.1'.tr,
  'live_agreement_articale_5.2'.tr,
  'live_agreement_articale_5.2'.tr,
  'live_agreement_articale_6'.tr,
  'live_agreement_articale_6.1'.tr,
  'live_agreement_articale_6.2'.tr,
  'live_agreement_articale_7'.tr,
  'live_agreement_articale_7.1'.tr,
  'live_agreement_articale_7.2'.tr,
  'live_agreement_articale_8'.tr,
  'live_agreement_articale_8.1'.tr,
  'live_agreement_articale_8.2'.tr,
 

];


}