


import 'package:muhammad_zubair_s_application4/core/app_export.dart';

class PrivacyPolicyController extends GetxController{
 List content=[
  {
    'title':'privacy_protection_title_1'.tr,
    'description':'privacy_protection_title_1_description'.tr
  },
  {
    'title':'privacy_protection_title_1.1'.tr,
    'description':'privacy_protection_title_1.1_description'.tr
  },
  {
    'title':'privacy_protection_title_1.2'.tr,
    'description':'privacy_protection_title_1.2_description'.tr
  },
  {
    'title':'privacy_protection_title_1.3'.tr,
    'description':'privacy_protection_title_1.3_description'.tr
  },
  {
    'title':'privacy_protection_title_1.4'.tr,
    'description':'privacy_protection_title_1.4_description'.tr
  },
  {
    'title':'privacy_protection_title_1.5'.tr,
    'description':'privacy_protection_title_1.5_description'.tr
  },
  {
    'title':'privacy_protection_title_1.6'.tr,
    'description':'privacy_protection_title_1.6_description'.tr
  },
  {
    'title':'privacy_protection_title_2'.tr,
    'description':'privacy_protection_title_2_description'.tr
  },
  {
    'title':'privacy_protection_title_2.1'.tr,
    'description':'privacy_protection_title_2.1_description'.tr
  },
  {
    'title':'privacy_protection_title_2.2'.tr,
    'description':'privacy_protection_title_2.2_description'.tr
  },
  {
    'title':'privacy_protection_title_2.3'.tr,
    'description':'privacy_protection_title_2.3_description'.tr
  },
  {
    'title':'privacy_protection_title_2.4'.tr,
    'description':'privacy_protection_title_2.4_description'.tr
  },
  {
    'title':'privacy_protection_title_2.4'.tr,
    'description':'privacy_protection_title_2.4_description'.tr
  },
  {
    'title':'privacy_protection_title_2.5'.tr,
    'description':'privacy_protection_title_2.5_description'.tr
  },
  {
    'title':'privacy_protection_title_2.6'.tr,
    'description':'privacy_protection_title_2.6_description'.tr
  },
  {
    'title':'privacy_protection_title_2.7'.tr,
    'description':'privacy_protection_title_2.7_description'.tr
  },
  {
    'title':'privacy_protection_title_2.8'.tr,
    'description':'privacy_protection_title_2.8_description'.tr
  },
  {
    'title':'privacy_protection_title_2.9'.tr,
    'description':'privacy_protection_title_2.9_description'.tr
  },
  {
    'title':'privacy_protection_title_2.10'.tr,
    'description':'privacy_protection_title_2.10_description'.tr
  },
  {
    'title':'privacy_protection_title_2.11'.tr,
    'description':'privacy_protection_title_2.11_description'.tr
  },
  {
    'title':'privacy_protection_title_2.12'.tr,
    'description':'privacy_protection_title_2.12_description'.tr
  },
  {
    'title':'privacy_protection_title_2.13'.tr,
    'description':'privacy_protection_title_2.13_description'.tr
  },
  {
    'title':'privacy_protection_title_2.14'.tr,
    'description':'privacy_protection_title_2.14_description'.tr
  },
  {
    'title':'privacy_protection_title_2.15'.tr,
    'description':'privacy_protection_title_2.15_description'.tr
  },
];
}